// Generated by https://quicktype.io

export interface ImgurResponse {
    id:            string;
    deletehash:    string;
    account_id:    null;
    account_url:   null;
    ad_type:       null;
    ad_url:        null;
    title:         null;
    description:   null;
    name:          string;
    type:          string;
    width:         number;
    height:        number;
    size:          number;
    views:         number;
    section:       null;
    vote:          null;
    bandwidth:     number;
    animated:      boolean;
    favorite:      boolean;
    in_gallery:    boolean;
    in_most_viral: boolean;
    has_sound:     boolean;
    is_ad:         boolean;
    nsfw:          null;
    link:          string;
    tags:          any[];
    datetime:      number;
    mp4:           string;
    hls:           string;
}
